### ISSUE TITLE
`lesson-start` branch not found.

### ISSUE THREAD

**Issue by tofuyaki** [kanawish/android-mvi-sample#7]
Hi.

I started this tutorial.
But `lesson-start` branch not fonud.
https://caster.io/lessons/android-mvi-setting-up-our-application

Which branch should I checkout?

**Comment by kanawish** [comment]
I believe you're looking for the ~[caster/lesson-start](https://github.com/kanawish/android-mvi-sample/tree/caster/lesson-start)~ [lesson/setting-up](https://github.com/kanawish/android-mvi-sample/tree/lesson/setting-up)  branch. Sorry for the late reply!

Quick tip, the branches are all in chronological order. You'll see them more clearly listed with your favourite git client, or looking at the commit history https://github.com/kanawish/android-mvi-sample/commits/master

Also the commit history comments have episode titles in them there.

**Comment by kanawish** [comment]
[lol, so bad, many apologies, I noticed these issues are from 2019! I was more focused on folks asking Q. on the caster feedback forums.]
